require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require "./app/api"
  end
end

task :console do
  system "./script/console"
end

task :server do
  system "bundle exec rackup -p 4567"
end
